// <auto-generated />
using System;
using Inventory_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Inventory_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260531174529_StartingProducts")]
    partial class StartingProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Inventory_API.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 5, 31, 15, 46, 18, 0, DateTimeKind.Utc),
                            Description = "Mrežni kabel U/FTP Cat.6A 5m",
                            ItemName = "Ethernet kabel",
                            Price = 6.99m,
                            Quantity = 25
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 5, 31, 15, 46, 18, 0, DateTimeKind.Utc),
                            Description = "8-portni gigabit switch",
                            ItemName = "Mrežni preklopnik",
                            Price = 30.00m,
                            Quantity = 5
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 5, 31, 15, 46, 18, 0, DateTimeKind.Utc),
                            Description = "Monofazni, 16A, B karakteristika, 10kA",
                            ItemName = "Strujni prekidač",
                            Price = 5.00m,
                            Quantity = 15
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 5, 31, 15, 46, 18, 0, DateTimeKind.Utc),
                            Description = "FG16(OR)16, bakar",
                            ItemName = "Kabel 4x50",
                            Price = 80.00m,
                            Quantity = 35
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
